name: mascotas_citas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  timeago: ^3.3.0
  url_launcher: ^6.3.1
  app_links: ^6.4.0
  get_it: ^8.0.3
  flutter_secure_storage_x: ^10.2.2
  provider: ^6.1.4
  flutter_svg: ^2.0.17
  flutter_screenutil: ^5.9.3
  image_picker: 1.1.2
  flutter_onboarding_slider: ^1.0.11
  flutter_web_auth_2: ^4.1.0
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/logos/google_logo.svg
  - assets/logos/logo_wildlove_nombre.png
  - assets/propietarios/  # Carpeta con fotos de propietarios
  - assets/mascotas/      # Carpeta con fotos de mascotas
    
